# SLU09 - Classification With Logistic Regression: Exercise notebook

In [ ]:
import pandas as pd 
import numpy as np 
import hashlib

In this notebook you will practice the following: 

    - What classification is for
    - Logistic regression
    - Cost function
    - Binary classification
    
You thought that you would get away without implementing your own little Logistic Regression? Hah!


# Exercise 1. Implement the Exponential part of Sigmoid Function


In the first exercise, you will implement **only the piece** of the sigmoid function where you have to use an exponential. 

Here's a quick reminder of the formula:

$$\hat{p} = \frac{1}{1 + e^{-z}}$$

In this exercise we only want you to complete the exponential part given the values of b0, b1, x1, b2 and x2:

$$e^{-z}$$

Recall that z has the following formula:

$$z = \beta_0 + \beta_1 x_1 + \beta_2 x_2$$

**Hint: Divide your z into pieces by Betas, I've left the placeholders in there!**

In [ ]:
def exponential_z_function(beta0, beta1, beta2, x1, x2):
    """ 
    Implementation of the exponential part of 
    the sigmoid function manually. In this exercise you 
    have to compute the e raised to the power -z. Z is calculated
    according to the following formula: b0+b1x1+b2x2. 
    
    You can use the inputs given to generate the z.
    
    Args:
        beta0 (np.float64): value of the intercept
        beta1 (np.float64): value of first coefficient
        beta2 (np.float64): value of second coefficient
        x1 (np.float64): value of first variable
        x2 (np.float64): value of second variable

    Returns:
        exp_z (np.float64): the exponential part of
        the sigmoid function

    """
    
    # hint: obtain the exponential part
    # using np.exp()
    
    
    # Complete the following
    #beta0 = ...
    #b1_x1 = ...
    #b2_x2 = ...
    
    #exp_z = ...
    
    # YOUR CODE HERE
    raise NotImplementedError()
    return exp_z

In [ ]:
value_arr = [1, 2, 1, 1, 0.5]

exponential = exponential_z_function(
    value_arr[0], value_arr[1], value_arr[2], value_arr[3], value_arr[4])

np.testing.assert_almost_equal(np.round(exponential,3), 0.030)

Expected output:

    Exponential part: 0.03

# Exercise 2: Make a Prediction

The next step is to implement a function that receives an observation and returns the predicted probability with the sigmoid function.

For instance, we can make a prediction given a model with data and coefficients by using the sigmoid:

$$\hat{p} = \frac{1}{1 + e^{-z}}$$

Where Z is the linear equation - you can't use the same function that you used above for the Z part as the input are now two arrays, one with the train data (x1, x2, ..., xn) and another with the coefficients (b0, b1, .., bn).

**Complete here:**

In [ ]:
def predict_proba(data, coefs):
    """ 
    Implementation of a function that returns 
    predicted probabilities for an observation.
    
    In the train array you will have 
    the data values (corresponding to the x1, x2, .. , xn).
    
    In the coefficients array you will have
    the coefficients values (corresponding to the b0, b1, .., bn).
    
    In this exercise you should be able to return a float 
    with the calculated probabilities given an array of size (1, n). 
    The resulting value should be a float (the predicted probability)
    with a value between 0 and 1. 
    
    Note: Be mindful that the input is completely different from 
    the function above - you receive two arrays in this functions while 
    in the function above you received 5 floats - each corresponding
    to the x's and b's.
    
    Args:
        data (np.array): a numpy array of shape (n)
            - n: number of variables
        coefs (np.array): a numpy array of shape (n + 1, 1)
            - coefs[0]: intercept
            - coefs[1:]: remaining coefficients

    Returns:
        proba (float): the predicted probability for a data example.

    """

    # hint: you have to implement your z in a vectorized 
    # way aka using vector multiplications - it's different from what you have done above
    
    # hint: don't forget about adding an intercept to the train data!
    
    # YOUR CODE HERE
    raise NotImplementedError()
    
    
    return proba

In [ ]:
x = np.array([-1.2, -1.5])
coefficients = np.array([0 ,4, -1])
np.testing.assert_almost_equal(round(predict_proba(x, coefficients),3),0.036)

x_1 = np.array([-1.5, -1, 3, 0])
coefficients_1 = np.array([0 ,2.1, -1, 0.5, 0])

np.testing.assert_almost_equal(round(predict_proba(x_1, coefficients_1),3),0.343)

Expected output:

    Predicted probabilities for example with 2 variables:  0.036
    
    Predicted probabilities for example with 3 variables:  0.343

# Exercise 3: Compute the Maximum Log-Likelihood Cost Function

As you will implement stochastic gradient descent, you need to calculate the cost function (the Maximum Log-Likelihood) for each prediction, checking how much you will penalize each example according to the difference between the calculated probability and its true value: 

$$H_{\hat{p}}(y) =  - (y \log(\hat{p}) + (1-y) \log (1-\hat{p}))$$

In the next exercise, you will loop through some examples stored in an array and calculate the cost function for the full dataset. Recall that the formula to generalize the cost function across several examples is: 

$$H_{\hat{p}}(y) = - \frac{1}{N}\sum_{i=1}^{N} \left [{ y_i \ \log(\hat{p}_i) + (1-y_i) \ \log (1-\hat{p}_i)} \right ]$$

You will basically simulate what stochastic gradient descent does without updating the coefficients - computing the log for each example, sum each log-loss and then averaging the result across the number of observations in the x dataset/array.

In [ ]:
import math

def max_log_likelihood_cost_function(var_x, coefs, var_y):
    """ 
    Implementation of a function that returns the Maximum-Log-Likelihood loss
    
    Args:
        var_x (np.array): array with x training data of size (m, n) shape 
        where m is the number of observations and n the number of columns
        coefs (float64): an array with the coefficients to apply of size (1, n+1)
        where n is the number of columns plus the intercept.
        var_y (float64): an array with integers with the real outcome per 
        example.
        
    Returns:
        loss (np.float): a float with the resulting log loss for the 
        entire data.

    """
    
    # A list of hints that you can follow:
    
    # - you already computed a probability for an example so you might be able to reuse the function
    
    # - Store number of examples that you have to loop through
    
    #Steps to follow:
    # 1. Initialize loss
    # 2. Loop through every example 
        # Hint: if you don't use the function from above to predict probas 
        # don't forget to add the intercept to the X_array!
        # 2.1 Calculate probability for each example
        # 2.2 Compute log loss
            # Hint: maybe separating the log loss will help you avoiding get confused inside all the parenthesis
        # 2.3 Sum the computed loss for the example to the total log loss
    # 3. Divide log loss by the number of examples (don't forget that the log loss 
        # has to return a positive number!)
    
    # YOUR CODE HERE
    raise NotImplementedError()
    return total_loss

In [ ]:
x = np.array([[-2, -2], [3.5, 0], [6, 4]])
coefficients = np.array([[0 ,2, -1]])
y = np.array([[1],[1],[0]])
np.testing.assert_almost_equal(round(max_log_likelihood_cost_function(x, coefficients, y),3),3.376)

coefficients_1 = np.array([[3 ,4, -0.6]])
x_1 = np.array([[-4, -4], [6, 0], [3, 2], [4, 0]])
y_1 = np.array([[4],[4],[2],[1.5]])

np.testing.assert_almost_equal(round(max_log_likelihood_cost_function(x_1, coefficients_1, y_1),3),-15.475)


Expected output:
    
    Computed log loss for first training set:  3.376
    
    Computed log loss for second training set:  -15.475

# Exercise 4: Compute a first pass on Stochastic Gradient Descent

Now that we know how to calculate probabilities and the cost function, let's do an interesting exercise - computing the derivatives and updating our coefficients. Here you will do a full pass on a bunch of examples, computing the gradient descent for each time you see one of them.

In this exercise, you should compute a single iteration of the gradient descent! 

You will basically use stochastic gradient descent but you will have to update the coefficients after
you see a new example - so each time your algorithm knows that he saw something way off (for example, 
returning a low probability for an example with outcome = 1) he will have a way (the gradient) to 
change the coefficients so that he is able to minimize the cost function.

## Quick reminders:

Remember our formulas for the gradient:

$$\beta_{0(t+1)} = \beta_{0(t)} - learning\_rate \frac{\partial H_{\hat{p}}(y)}{\partial \beta_{0(t)}}$$

$$\beta_{t+1} = \beta_t - learning\_rate \frac{\partial H_{\hat{p}}(y)}{\partial \beta_t}$$

which can be simplified to

$$\beta_{0(t+1)} = \beta_{0(t)} + learning\_rate \left [(y - \hat{p}) \ \hat{p} \ (1 - \hat{p})\right]$$

$$\beta_{t+1} = \beta_t + learning\_rate \left [(y - \hat{p}) \ \hat{p} \ (1 - \hat{p}) \ x \right]$$

You will have to initialize the coefficients in some way. If you have a training set $X$, you can initialize them to zero, this way:
```python
coefficients = np.zeros(X.shape[1]+1)
```

where the $+1$ is adding the intercept.

Note: We are doing a stochastic gradient descent so don't forget to go observation by observation and updating the coefficients every time!

**Complete here:**

In [ ]:
def compute_coefs_sgd(x_train, y_train, learning_rate = 0.1, verbose = False):
    """ 
    Implementation of a function that returns the a first iteration of 
    stochastic gradient descent.

    Args:
        x_train (np.array): a numpy array of shape (m, n)
            m: number of training observations
            n: number of variables
        y_train (np.array): a numpy array of shape (m,) with 
        the real value of the target.
        learning_rate (np.float64): a float

    Returns:
        coefficients (np.array): a numpy array of shape (n+1,)

    """
    
    # A list of hints that might help you:
    
    # 1. Calculate the number of observations
    
    # 2. Initialize the coefficients array with zeros
            # hint: use np.zeros()    
    
    # 3. Run the stochastic gradient descent and update the coefficients after each observation    
        # 3.1 Compute the predicted probability - you can use a function we have done previously 
        # 3.2 Update intercept
        # 3.3 Update the rest of the coefficients by looping through each variable
    
    # YOUR CODE HERE
    raise NotImplementedError()
    
    return coefficients

In [ ]:
#Test 1
x_train = np.array([[1,2,4], [2,4,9], [2,1,4], [9,2,10]])
y_train = np.array([0,2.2,0,2.3])
learning_rate = 0.1

np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train, y_train, learning_rate)[0],3),0.022)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train, y_train, learning_rate)[1],3),0.081)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train, y_train, learning_rate)[2],3),0.140)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train, y_train, learning_rate)[3],3),0.320)

#Test 2
x_train_1 = np.array([[4,4,2,6], [1,5,7,2], [3,1,2,1], [8,2,9,5], [2,2,9,4]])
y_train_1 = np.array([0,1.3,0,1.3,1.2])

np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train_1, y_train_1, learning_rate).max(),3) ,0.277)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train_1, y_train_1, learning_rate).min(),3) ,0.015)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train_1, y_train_1, learning_rate).mean(),3),0.102)
np.testing.assert_almost_equal(round(compute_coefs_sgd(x_train_1, y_train_1, learning_rate).var(),3) ,0.008)


# Exercise 5: Normalize Data

To get this concept in your head, let's do a quick and easy function to normalize the data using a MaxMin approach. It is crucial that your variables are adjusted between $[0;1]$ (normalized) or standardized so that you can correctly analyze some logistic regression coefficients for your possible future employer.

You only have to implement this formula

$$ x_{normalized} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

Don't forget that the `axis` argument is critical when obtaining the maximum, minimum and mean values! As you want to obtain the maximum and minimum values of each individual feature, you have to specify `axis=0`. Thus, if you wanted to obtain the maximum values of each feature of data $X$, you would do the following:

```python
X_max = np.max(X, axis=0)
```

Not an assertable question but can you remember why it is important to normalize data for Logistic Regression?

**Complete here:**

In [ ]:
def normalize_data_function(data):
    """ 
    Implementation of a function that normalizes your data variables
    
    Args:
        data (np.array): a numpy array of shape (m, n)
            m: number of observations
            n: number of variables

    Returns:
        normalized_data (np.array): a numpy array of shape (m, n)

    """
    # Compute the numerator first 
    # you can use np.min()
    # numerator = ...
    
    # Compute the denominator
    # you can use np.max() and np.min()
    # denominator = ...
    
    
    # YOUR CODE HERE
    raise NotImplementedError()
    return normalized_data

In [ ]:
data = np.array([[7,7,3], [2,2,11], [9,5,2], [0,9,5], [10,1,3], [1,5,2]])
normalized_data = normalize_data_function(data)
print('Before normalization:')
print(data)
print('\n-------------------\n')
print('After normalization:')
print(normalized_data)

Expected output:
    
    Before normalization:
    [[ 7  7  3]
     [ 2  2 11]
     [ 9  5  2]
     [ 0  9  5]
     [10  1  3]
     [ 1  5  2]]

    -------------------

After normalization:

    [[0.7        0.75       0.11111111]
     [0.2        0.125      1.        ]
     [0.9        0.5        0.        ]
     [0.         1.         0.33333333]
     [1.         0.         0.11111111]
     [0.1        0.5        0.        ]]

In [ ]:
data = np.array([[2,2,11,1], [7,5,1,3], [9,5,2,6]])
normalized_data = normalize_data_function(data)
np.testing.assert_almost_equal(round(normalized_data.max(),3),1.0)
np.testing.assert_almost_equal(round(normalized_data.mean(),3),0.518)
np.testing.assert_almost_equal(round(normalized_data.var(),3),0.205)


data = np.array([[1,3,1,3], [9,5,3,1], [2,2,4,6]])
normalized_data = normalize_data_function(data)
np.testing.assert_almost_equal(round(normalized_data.mean(),3),0.460)
np.testing.assert_almost_equal(round(normalized_data.std(),3),0.427)

# Exercise 6: Training a Logistic Regression with Sklearn

In this exercise, we will load a dataset related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The goal is to predict whether the client will subscribe (1/0) to a term deposit (variable y) ([link to dataset](http://archive.ics.uci.edu/ml/datasets/Bank+Marketing))

Prepare to use your sklearn skills!

In [ ]:
# We will load the dataset for you
bank = pd.read_csv('data/bank.csv', delimiter=";")
bank.head()

In this exercise, you need to do the following: 

- Select an array/Series with the target variable (y) 

- Select an array/dataframe with the X numeric variables (age, balance, day, month, duration, campaign and pdays) 

- Scale all the X variables - normalize using Max / Min method. 

- Fit a logistic regression for a maximum of 100 epochs and random state = 100. 

- Return an array of the predicted probas and return the coefficients

After this, feel free to explore your predictions! As a bonus why don't you construct a decision boundary using two variables eh? :-)

In [ ]:
from sklearn.linear_model import LogisticRegression

def train_model_sklearn(dataset):
    '''
    Returns the predicted probas and coefficients 
    of a trained logistic regression on the Titanic Dataset.
    
    Args:
        dataset(pd.DataFrame): dataset to train on.
    
    Returns:
        probas (np.array): Array of floats with the probability 
        of surviving for each passenger
        coefficients (np.array): Returned coefficients of the 
        trained logistic regression.
    '''
    
    # leave this np.random seed here
    
    np.random.seed(100)
    
    # List of hints:
    
    # 1. Use the Survived variable as y
    
    # 2. Select the Numerical variables for X 
    # hint: use pandas .loc or indexing!    
    
    # 3. Scale the X dataset - you can use a function we have already
    # constructed or resort to the sklearn implementation
    
    # 4. Define logistic regression from sklearn with max iter = 100 also add random_state = 100
    # Hint: for epochs look at the max_iter hyper param!
    
    # 5. Fit logistic
    
    # 6. Obtain probability of surviving
    
    # 7. Obtain Coefficients from logistic regression
    # Hint: see the sklearn logistic regression documentation if you do not know how to do this 
    # No need to return the intercept, just the variable coefficients!
    
    # YOUR CODE HERE
    raise NotImplementedError()
    return probas, coef
    

In [ ]:
probas, coef = train_model_sklearn(bank)

# Testing Probas
max_probas = probas.max()
np.testing.assert_almost_equal(max_probas, 0.997, 2)
min_probas = probas.min()
np.testing.assert_almost_equal(min_probas, 0.008, 2)
mean_probas = probas.mean()
np.testing.assert_almost_equal(mean_probas, 0.115, 2)
std_probas = probas.std()
np.testing.assert_almost_equal(std_probas, 0.115, 2)
sum_probas = probas.sum()
np.testing.assert_almost_equal(sum_probas*0.001, 0.521, 2)

# Testing Coefs
max_coef = coef[0].max()
np.testing.assert_almost_equal(max_coef*0.1, 0.87, 1)
min_coef = coef[0].min()
np.testing.assert_almost_equal(min_coef*0.1, -0.18, 1)
mean_coef = coef[0].mean()
np.testing.assert_almost_equal(mean_coef*0.1, 0.21, 1)
std_coef = coef[0].std()
np.testing.assert_almost_equal(std_coef*0.1, 0.35, 1)
sum_probas = coef[0].sum()
np.testing.assert_almost_equal(sum_probas*0.1, 1.06, 1)